### PR TITLE
Merge with changes made over the past 18 months

### PR DESCRIPTION
**Pull request by salynch**
* Make Context.Undoer not auto-undo by default because this behavior is unpredictable
* Add tag to Undoer for debugging
* Make PROPERTY_OPTIMIZE_SELECT_FIELDS false by default
* Add support for OFFSET SQL keyword in MSSQL (untested with other DB's)
* Add support for ConnectionAdapter class in SchemaExtractorBase

### CODE REVIEW

**Comment by salynch** [comment]
Additional changes are coming... need to commit them tomorrow.

**Comment by keredson** [comment]
Scott, having the select optimizer off by default: is that still due to no home dirs on the cluster?  Maybe that could just be turned off with a prop file, rather that default for all?

**Comment by salynch** [comment]
That's certainly one of the reasons, but I can't recall all of them. We
just found a lot more problems with it than we found that it helped.

**Comment by salynch** [comment]
Also, some of the code related to the ConnectionAdapter is
incomplete/incorrect - that's what I need to push tomorrow.

**Pull request closed without merging**
